# Generated by Django 5.0.1 on 2024-01-19 11:33

import django.db.models.deletion
import django.utils.timezone
import erpservices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_no', models.CharField(max_length=100)),
                ('block_no', models.CharField(max_length=100)),
                ('remaining_address', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'appartment_info',
            },
        ),
        migrations.CreateModel(
            name='Invite_Code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_identifier', models.CharField(default=erpservices.models.Invite_Code.generate_random_string, max_length=5)),
            ],
            options={
                'db_table': 'invite_code',
            },
        ),
        migrations.CreateModel(
            name='Notification_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'notification_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_display_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Admin_Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_customer_admin_set', to=settings.AUTH_USER_MODEL)),
                ('_customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_customer_customer_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_customer',
            },
        ),
        migrations.CreateModel(
            name='Appartment_Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('appartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.appartment_info')),
            ],
            options={
                'db_table': 'appartment_customer',
            },
        ),
        migrations.CreateModel(
            name='Invite_Code_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invite_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.invite_code')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_code_user',
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_message', models.CharField(max_length=100)),
                ('notification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_set', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.notification_type')),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificationModel',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=None)),
                ('payment_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.paymentstype')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Roles_Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.roles')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roles_users',
            },
        ),
    ]
