# Generated by Django 5.0.1 on 2024-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'residence_status',
            },
        ),
    ]
