# Generated by Django 5.0.1 on 2024-01-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0004_alter_notificationmodel_receiver'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notificationmodel',
            table='notification',
        ),
    ]
