# Generated by Django 5.0.1 on 2024-01-22 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0005_alter_notificationmodel_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints_subject', models.CharField(max_length=100)),
                ('complaints_body', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
        migrations.CreateModel(
            name='Complaints_Status_Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'complaints_status_types',
            },
        ),
        migrations.CreateModel(
            name='Complaints_Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_desc', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'complaints_subject',
            },
        ),
        migrations.CreateModel(
            name='Complaints_Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.complaints')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.complaints_status_types')),
            ],
            options={
                'db_table': 'complaints_status',
            },
        ),
        migrations.CreateModel(
            name='Complaints_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.complaints')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'complaints_user',
            },
        ),
    ]
