# Generated by Django 5.0.1 on 2024-01-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0006_complaints_complaints_status_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaints_current_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.complaints_status_types'),
        ),
    ]
