# Generated by Django 5.0.1 on 2024-01-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0007_complaints_complaints_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='complaints_current_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erpservices.complaints_status_types'),
        ),
    ]
