# Generated by Django 5.0.1 on 2024-01-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0011_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='profileImage',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
