# Generated by Django 5.0.1 on 2024-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0012_userinformation_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='family_members_count',
            field=models.IntegerField(blank=True),
        ),
    ]
