# Generated by Django 5.0.1 on 2024-01-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0013_alter_userinformation_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='profileImage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.image_user'),
        ),
    ]
