# Generated by Django 5.0.1 on 2024-01-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0014_alter_userinformation_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='contact_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='family_members_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='profileImage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erpservices.image_user'),
        ),
    ]
