# Generated by Django 5.0.1 on 2024-01-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0015_alter_userinformation_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='User',
            new_name='user',
        ),
    ]
