# Generated by Django 5.0.1 on 2024-02-16 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpservices', '0017_appartment_residence_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartmentResident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appartment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='erpservices.appartment_info')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appartment_resident',
            },
        ),
    ]
